#----------------spring配置------------------------
spring:
  profiles:
    active: dev
  web:
    resources:
      static-locations: [ classpath:/static/ ]
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      # 单个文件的最大值
      max-file-size: 10MB
      # 上传文件总的最大值
      max-request-size: 50MB
  datasource:
    # 解决中文乱码输入问题,其中UTC是统一标准世界时间。
    url: jdbc:mysql://localhost:3306/chai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filters: stat,wall
#      # 初始化，最小，最大连接数
#      initial-size: 3
#      min-idle: 3
#      max-active: 18
#      stat-view-servlet: # 配置监控页功能
#        enabled: true
#        login-username: admin
#        login-password: 123456
#
#      web-stat-filter: # 监控web
#        enabled: true
#        urlPattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#
#      filter:
#        stat: # 对上面filters里面的stat的详细配置
#          slow-sql-millis: 1000
#          logSlowSql: true
#          enabled: true
#        wall:
#          enabled: true
#          config:
#            drop-table-allow: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: redis123
    database: 0
    # 连 接 池 配 置
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 0
    # 超时时间
    timeout: 1000


#---------------server配置--------------------
server:
  port: 8080
  servlet:
    context-path: /
    session:
      # 超 时 时 间
      timeout: 120m
  # 默认错误页位置
  error:
    path: error


#----------------mybatis配置规则-----------------
mybatis-plus:
  mapper-locations: classpath*:**/xml/**.xml
  #  扫描Entity, 加入此设置方可在Mybatis的XML文件中使用实体类的Alias
  type-aliases-package: com.weiyu.chaitoufeng.domain.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#-------------- Pear 插 件 配 置 信 息---------------
chaitoufeng:
  security:
    # 开 启 超 级 管 理 员 账 号 -- 不需要验证权限
    super-auth-open: true
    # 超 级 管 理 员 账 号 -- 不需要验证权限
    super-admin: admin
    # 允 许 同 一 账 号 多 端 登 录 个 数
    maximum: 1
    # 记 住 密 码 KEY
    remember-key: PEAR_REMEMBER
    # 不 需 要 权 限 拦 截 的 接 口 配 置
    open-api:
      - /     # 开放前端视图
      - /index
      - /poem
      - /sentence
      - /author
      - /dynasty
      - /profile
      - /about
      - /search
      - /poem/**  # 前端数据接口
      - /home/**
      - /login/**  # 开放登录接口
      - /register  #开放注册接口
      - /system/captcha/** # 开放验证码接口
      - /error/** # 开放错误接口
      - /static/**  #开放静态资源
#      - /favicon.ico # 开放FAVICON

  # 上传配置
  upload:
    windows-path: C:\Users\wish_dq\Desktop\毕业\ChaiTouFeng\home\uploads\
    linux-path: /home/uploads/


# --------------Page Helper 分页配置------------------
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true